import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F9F9F9',
  },
  inputsTopTow: {
    borderColor: '#ccc',
    borderWidth: 1,
    width: 270,
    padding: 10,
    borderRadius: 10,
    backgroundColor: '#fff',
  },
  btn_yellow: {
    backgroundColor: '#FCDF6F',
    width: 300,
    borderRadius: 10,
    padding: 10,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 20,
  },
  heading1: {
    marginTop: 20,
    marginBottom: 21,
    fontSize: 20,
    color: 'black',
    // fontWeight:'bold',
    textAlign: 'center',
    fontFamily: 'ProximaNovaBold',
  },
  main_container: {
    marginHorizontal: 10,
    flex: 8,
    alignItems: 'center',
    marginTop: 15,
  },
  inputsTopTow: {
    borderColor: '#ccc',
    borderWidth: 1,
    width: 270,
    padding: 10,
    borderRadius: 10,
    backgroundColor: '#fff',
    fontFamily: 'ProximaNova',
  },
  inputLabel: {
    color: 'black',
    opacity: 0.8,
    paddingBottom: 2.7,
    fontSize: 15,
    fontFamily: 'ProximaNovaBold',
  },
  input_box: {
    marginBottom: 16,
  },
  smallInput: {
    width: 45,
    height: 45,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 10,
    borderColor: '#ccc',
    borderWidth: 1,
    borderRadius: 5,
    backgroundColor: 'white',
  },
  btn_yellow: {
    backgroundColor: '#FCDF6F',
    width: '84%',
    borderRadius: 10,
    padding: 10,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
    alignSelf: 'center',
  },
  btn_gray: {
    backgroundColor: '#ccc',
    width: '84%',
    borderRadius: 10,
    padding: 10,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
    alignSelf: 'center',
  },
  chooseButtons_container: {
    width: 270,
    flexDirection: 'row',
    backgroundColor: '#fff',
    justifyContent: 'center',
    height: 50,
    borderColor: '#ccc',
    borderWidth: 1,
    borderRadius: 7,
  },
  chooseButtons_container_active: {
    width: 270,
    flexDirection: 'row',
    backgroundColor: '#fff',
    justifyContent: 'center',
    height: 50,
    borderColor: '#ccc',
    //  borderWidth:1,
    borderRadius: 7,
  },
  btn1: {
    width: 135,
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
    borderColor: '#ccc',
    borderWidth: 1,
    borderTopLeftRadius: 0,
    borderBottomLeftRadius: 8,
    borderTopLeftRadius: 8,
  },
  btn2: {
    width: 135,
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
    borderColor: '#ccc',
    borderWidth: 1,
    borderTopRightRadius: 8,
    borderBottomRightRadius: 8,
  },
  btn2_active: {
    width: 135,
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
    borderLeftColor: '#ccc',
    // borderLeftWidth:1,
    backgroundColor: '#FCDF6F',
    borderColor: '#ccc',
    borderTopRightRadius: 8,
    borderBottomRightRadius: 8,
  },
  btn1_active: {
    width: 135,
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
    borderLeftColor: '#ccc',
    // borderLeftWidth:1,
    backgroundColor: '#FCDF6F',
    borderColor: '#ccc',
    borderTopLeftRadius: 8,
    borderBottomLeftRadius: 8,
  },
  timeTxt: {
    fontFamily: 'ProximaNova',
  },
  experience: {
    paddingLeft: 12,
    paddingTop: 14,
    fontFamily: 'ProximaNova',
    fontSize: 15,
    fontWeight: '600',
  },
});

export default styles;
